# Makefile generated by OpenModelica
# Platform: linux64

# Simulations use -O3 by default
CC=clang
CXX=clang++
LINK=clang -shared
EXEEXT=
DLLEXT=.so
CFLAGS_BASED_ON_INIT_FILE=
DEBUG_FLAGS=-Os
CFLAGS=$(CFLAGS_BASED_ON_INIT_FILE) $(DEBUG_FLAGS) -fPIC -mfpmath=sse -fno-dollars-in-identifiers ${MODELICAUSERCFLAGS}   
CPPFLAGS= -I"/usr/bin/../include/omc/c" -I. -DOPENMODELICA_XML_FROM_FILE_AT_RUNTIME -DOMC_MODEL_PREFIX=sCO2PBCalculator_Using_PinchPHX -DOMC_NUM_MIXED_SYSTEMS=0 -DOMC_NUM_LINEAR_SYSTEMS=3 -DOMC_NUM_NONLINEAR_SYSTEMS=48 -DOMC_NDELAY_EXPRESSIONS=0 -DOMC_NVAR_STRING=0
LDFLAGS=-L"/usr/bin/../lib/x86_64-linux-gnu/omc" -L"/usr/bin/../lib" -Wl,-rpath,"/usr/bin/../lib/x86_64-linux-gnu/omc" -Wl,-rpath,"/usr/bin/../lib"     -Wl,--no-as-needed -Wl,--disable-new-dtags -lSimulationRuntimeC -llapack -lblas -lm -lm -lomcgc -lpthread -rdynamic -Wl,--no-undefined 
DIREXTRA=-L"/home/philgun/Documents/codecodecode/codecodecode/surrogate-sCO2-4/simulation"
MAINFILE=sCO2PBCalculator_Using_PinchPHX.c
MAINOBJ=sCO2PBCalculator_Using_PinchPHX.o
CFILES=sCO2PBCalculator_Using_PinchPHX_functions.c sCO2PBCalculator_Using_PinchPHX_records.c \
sCO2PBCalculator_Using_PinchPHX_01exo.c sCO2PBCalculator_Using_PinchPHX_02nls.c sCO2PBCalculator_Using_PinchPHX_03lsy.c sCO2PBCalculator_Using_PinchPHX_04set.c sCO2PBCalculator_Using_PinchPHX_05evt.c sCO2PBCalculator_Using_PinchPHX_06inz.c sCO2PBCalculator_Using_PinchPHX_07dly.c \
sCO2PBCalculator_Using_PinchPHX_08bnd.c sCO2PBCalculator_Using_PinchPHX_09alg.c sCO2PBCalculator_Using_PinchPHX_10asr.c sCO2PBCalculator_Using_PinchPHX_11mix.c sCO2PBCalculator_Using_PinchPHX_12jac.c sCO2PBCalculator_Using_PinchPHX_13opt.c sCO2PBCalculator_Using_PinchPHX_14lnz.c \
sCO2PBCalculator_Using_PinchPHX_15syn.c sCO2PBCalculator_Using_PinchPHX_16dae.c sCO2PBCalculator_Using_PinchPHX_17inl.c 

OFILES=$(CFILES:.c=.o)
GENERATEDFILES=$(MAINFILE) sCO2PBCalculator_Using_PinchPHX.makefile sCO2PBCalculator_Using_PinchPHX_literals.h sCO2PBCalculator_Using_PinchPHX_functions.h $(CFILES)

.PHONY: omc_main_target clean bundle

# This is to make sure that sCO2PBCalculator_Using_PinchPHX_*.c are always compiled.
.PHONY: $(CFILES)

omc_main_target: $(MAINOBJ) sCO2PBCalculator_Using_PinchPHX_functions.h sCO2PBCalculator_Using_PinchPHX_literals.h $(OFILES)
	$(CC) -I. -o sCO2PBCalculator_Using_PinchPHX$(EXEEXT) $(MAINOBJ) $(OFILES) $(CPPFLAGS) $(DIREXTRA)  "-L/usr/bin/../lib/x86_64-linux-gnu/omc" -Wl,-rpath="/usr/bin/../lib/x86_64-linux-gnu/omc" "-L/usr/bin/../lib/" -Wl,-rpath="/usr/bin/../lib/" "-L/home/philgun/.openmodelica/binaries/SolarTherm" -Wl,-rpath="/home/philgun/.openmodelica/binaries/SolarTherm" "-L/home/philgun/.local/lib/omlibrary/SolarTherm/Resources/Library/x86_64-linux" -Wl,-rpath="/home/philgun/.local/lib/omlibrary/SolarTherm/Resources/Library/x86_64-linux" "-L/home/philgun/.local/lib/omlibrary/SolarTherm/Resources/Library/linux64" -Wl,-rpath="/home/philgun/.local/lib/omlibrary/SolarTherm/Resources/Library/linux64" "-L/home/philgun/.local/lib/omlibrary/SolarTherm/Resources/Library" -Wl,-rpath="/home/philgun/.local/lib/omlibrary/SolarTherm/Resources/Library" -lModelicaStandardTables -lModelicaIO -lModelicaMatIO -lzlib "-L/home/philgun/.openmodelica/binaries/Modelica" -Wl,-rpath="/home/philgun/.openmodelica/binaries/Modelica" "-L/usr/lib/omlibrary/Modelica 3.2.2/Resources/Library/x86_64-linux" -Wl,-rpath="/usr/lib/omlibrary/Modelica 3.2.2/Resources/Library/x86_64-linux" "-L/usr/lib/omlibrary/Modelica 3.2.2/Resources/Library/linux64" -Wl,-rpath="/usr/lib/omlibrary/Modelica 3.2.2/Resources/Library/linux64" "-L/usr/lib/omlibrary/Modelica 3.2.2/Resources/Library" -Wl,-rpath="/usr/lib/omlibrary/Modelica 3.2.2/Resources/Library" -lModelicaExternalC $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)
clean:
	@rm -f sCO2PBCalculator_Using_PinchPHX_records.o $(MAINOBJ)

bundle:
	@tar -cvf sCO2PBCalculator_Using_PinchPHX_Files.tar $(GENERATEDFILES)