# Makefile generated by OpenModelica
# Platform: linux64

# Simulations use -O3 by default
CC=clang
CXX=clang++
LINK=clang -shared
EXEEXT=
DLLEXT=.so
CFLAGS_BASED_ON_INIT_FILE=
DEBUG_FLAGS=-Os
CFLAGS=$(CFLAGS_BASED_ON_INIT_FILE) $(DEBUG_FLAGS) -fPIC -mfpmath=sse -fno-dollars-in-identifiers ${MODELICAUSERCFLAGS}   
CPPFLAGS="-I/home/philgun/.local/lib/omlibrary/SolarTherm/Resources/Include" -I"/usr/bin/../include/omc/c" -I. -DOPENMODELICA_XML_FROM_FILE_AT_RUNTIME -DOMC_MODEL_PREFIX=sCO2SurrogatePBRig -DOMC_NUM_MIXED_SYSTEMS=0 -DOMC_NUM_LINEAR_SYSTEMS=3 -DOMC_NUM_NONLINEAR_SYSTEMS=47 -DOMC_NDELAY_EXPRESSIONS=0 -DOMC_NVAR_STRING=0
LDFLAGS=-L"/usr/bin/../lib/x86_64-linux-gnu/omc" -L"/usr/bin/../lib" -Wl,-rpath,"/usr/bin/../lib/x86_64-linux-gnu/omc" -Wl,-rpath,"/usr/bin/../lib"     -Wl,--no-as-needed -Wl,--disable-new-dtags -lSimulationRuntimeC -llapack -lblas -lm -lm -lomcgc -lpthread -rdynamic -Wl,--no-undefined 
DIREXTRA=-L"/home/philgun/Documents/codecodecode/codecodecode/sCO2-surrogate-model/sCO2-test-data/simulation_surrogate"
MAINFILE=sCO2SurrogatePBRig.c
MAINOBJ=sCO2SurrogatePBRig.o
CFILES=sCO2SurrogatePBRig_functions.c sCO2SurrogatePBRig_records.c \
sCO2SurrogatePBRig_01exo.c sCO2SurrogatePBRig_02nls.c sCO2SurrogatePBRig_03lsy.c sCO2SurrogatePBRig_04set.c sCO2SurrogatePBRig_05evt.c sCO2SurrogatePBRig_06inz.c sCO2SurrogatePBRig_07dly.c \
sCO2SurrogatePBRig_08bnd.c sCO2SurrogatePBRig_09alg.c sCO2SurrogatePBRig_10asr.c sCO2SurrogatePBRig_11mix.c sCO2SurrogatePBRig_12jac.c sCO2SurrogatePBRig_13opt.c sCO2SurrogatePBRig_14lnz.c \
sCO2SurrogatePBRig_15syn.c sCO2SurrogatePBRig_16dae.c sCO2SurrogatePBRig_17inl.c 

OFILES=$(CFILES:.c=.o)
GENERATEDFILES=$(MAINFILE) sCO2SurrogatePBRig.makefile sCO2SurrogatePBRig_literals.h sCO2SurrogatePBRig_functions.h $(CFILES)

.PHONY: omc_main_target clean bundle

# This is to make sure that sCO2SurrogatePBRig_*.c are always compiled.
.PHONY: $(CFILES)

omc_main_target: $(MAINOBJ) sCO2SurrogatePBRig_functions.h sCO2SurrogatePBRig_literals.h $(OFILES)
	$(CC) -I. -o sCO2SurrogatePBRig$(EXEEXT) $(MAINOBJ) $(OFILES) $(CPPFLAGS) $(DIREXTRA)  "-L/usr/bin/../lib/x86_64-linux-gnu/omc" -Wl,-rpath="/usr/bin/../lib/x86_64-linux-gnu/omc" "-L/usr/bin/../lib/" -Wl,-rpath="/usr/bin/../lib/" "-L/home/philgun/.openmodelica/binaries/SolarTherm" -Wl,-rpath="/home/philgun/.openmodelica/binaries/SolarTherm" "-L/home/philgun/.local/lib/omlibrary/SolarTherm/Resources/Library/x86_64-linux" -Wl,-rpath="/home/philgun/.local/lib/omlibrary/SolarTherm/Resources/Library/x86_64-linux" "-L/home/philgun/.local/lib/omlibrary/SolarTherm/Resources/Library/linux64" -Wl,-rpath="/home/philgun/.local/lib/omlibrary/SolarTherm/Resources/Library/linux64" "-L/home/philgun/.local/lib/omlibrary/SolarTherm/Resources/Library" -Wl,-rpath="/home/philgun/.local/lib/omlibrary/SolarTherm/Resources/Library" -ltensorflow -lModelicaStandardTables -lModelicaIO -lModelicaMatIO -lzlib "-L/home/philgun/.openmodelica/binaries/Modelica" -Wl,-rpath="/home/philgun/.openmodelica/binaries/Modelica" "-L/usr/lib/omlibrary/Modelica 3.2.2/Resources/Library/x86_64-linux" -Wl,-rpath="/usr/lib/omlibrary/Modelica 3.2.2/Resources/Library/x86_64-linux" "-L/usr/lib/omlibrary/Modelica 3.2.2/Resources/Library/linux64" -Wl,-rpath="/usr/lib/omlibrary/Modelica 3.2.2/Resources/Library/linux64" "-L/usr/lib/omlibrary/Modelica 3.2.2/Resources/Library" -Wl,-rpath="/usr/lib/omlibrary/Modelica 3.2.2/Resources/Library" -lModelicaExternalC $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)
clean:
	@rm -f sCO2SurrogatePBRig_records.o $(MAINOBJ)

bundle:
	@tar -cvf sCO2SurrogatePBRig_Files.tar $(GENERATEDFILES)